name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:

  build:

    runs-on: KS-2

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sample-nodejs-app-v1:$(date +%s)
